### ISSUE TITLE
Syntax highlighting hangs when using a substring pattern with '

### ISSUE THREAD

**Issue by kpietak** [rehype-pretty/rehype-pretty-code#185]
I have come across a problem with highlighting sections of source code using a pattern/substring using [Nextra](https://github.com/shuding/nextra).

I am presenting code in Rust that implements lifetimes annotations marked with ' , for example:
`fn longer<'a>(a : &'a [i32], b : &'a [i32]) -> &'a [i32]`.

I am trying to highlight the annotation itself (`'a`) using the code: 
```
    ```rust /'a/
    fn longer_array<'a>(a : &'a [i32], b : &'a [i32]) -> &'a [i32] {
        ...
    }```
```
This syntax causes the page rendering to crash (even terminating the process causes the node to remain on).

The problem has been previously reported in the Nextra project (https://github.com/shuding/nextra/issues/2792) and was redirected here as a code rendering issue.

**Comment by atomiks** [comment]
[Nextra seems to be using `v0.9.11`](https://github.com/shuding/nextra/blob/12e9d31a022ff80f1de50f4fcff7dc7d8c7b41ef/packages/nextra/package.json#L139) which is a bit old now as the current version is `v0.13.0`. In `v0.12.1`, a bug was fixed with word highlighting that could cause an infinite loop, although I thought it was a regression introduced in `v0.12.0` 🤔 

Can you try to repro it using the latest version of `rehype-pretty-code` alone?

**Comment by kpietak** [comment]
I've reproduced the error using the current version (`v.0.13.0`). Here is the sample code (a modified demo):

```js
import { unified } from "unified";
import remarkParse from "remark-parse";
import remarkRehype from "remark-rehype";
import rehypeStringify from "rehype-stringify";
import rehypePrettyCode from "rehype-pretty-code";
 
async function main() {
  const file = await unified()
    .use(remarkParse)
    .use(remarkRehype)
    .use(rehypePrettyCode, {
      // See Options section below.
    })
    .use(rehypeStringify)
    .process(`\`\`\`rust /'a/
    
    fn longer_array<'a>(a : &'a [i32], b : &'a [i32]) -> &'a [i32] {
        
    }
    `);
 
  console.log(String(file));
}
 
main();
```

**Comment by pablofdezr** [comment]
Still reproduces on the latest release, **v0.14.3**.

## Minimal reproduction

```js
import { unified } from "unified";
import remarkParse from "remark-parse";
import remarkRehype from "remark-rehype";
import rehypeStringify from "rehype-stringify";
import rehypePrettyCode from "rehype-pretty-code";

const md = `\`\`\`js /Math.sin/
const s = Math.sin(x) + Math.sin(y);
\`\`\`
`;

await unified()
  .use(remarkParse)
  .use(remarkRehype)
  .use(rehypePrettyCode, { theme: "github-light" })
  .use(rehypeStringify)
  .process(md);

console.log("done"); // never printed -> synchronous infinite loop
```

This pegs one CPU core and never returns. Because the loop is synchronous, an
in-process timeout / `Promise.race` won't help — you have to kill the process.

## When it happens

The hang needs **both** conditions:

1. the pattern matches text that spans **more than one Shiki token** (contains a
   `.`, a space, a lifetime `'`, etc., which Shiki splits into separate spans), and
2. that match occurs **two or more times on the same line**.

- `/Math.sin/` once: fine.
- `/Math/` twice (single token): fine.
- `/Math.sin/` twice, `/c.json/` twice, or `/'a/` on a Rust line with two
  lifetimes: hangs.

## Root cause

In `packages/core/src/chars/charsHighlighter.ts` the loop keeps running while the
recomputed `textContent` still contains the pattern, excluding nodes marked with
`data-highlighted-chars-mark` or `rehype-pretty-code-visited`.

For a multi-token match, `wrapHighlightedChars` wraps the tokens in a new
`<mark>` but — unlike the single-token branch — never sets
`rehype-pretty-code-visited` on it. So on the next iteration
`getElementsToHighlight` re-finds the already-wrapped group (its text still
equals the pattern), `wrapHighlightedChars` bails out early because the wrapper's
first child is a `<span>` rather than a text node, and the second occurrence is
never consumed — the `while` condition stays true forever. With a single
occurrence the loop exits before the wrapper is re-scanned, which is why only the
repeated case hangs.

## Fix

Opened #272 with a fix + regression test: it marks the multi-token `<mark>`
group as visited (mirroring the single-token branch) so it is skipped on
rescans and every occurrence is highlighted, plus a progress guard that stops
the loop if an iteration consumes nothing. The full test suite passes with a new
fixture covering `/Math.sin/`, `/c.json/`, and the Rust `/'a/` case from this
issue.
